
PERPLEXITY_API_KEY = "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"
PERPLEXITY_MODEL = "sonar-pro"


FLASK_SECRET_KEY = "a_strong_default_secret_key_12345"


QLOAPPS_API_KEY = "2TIF3ZJMJGKPW3WU1ZVZ61PRQUZMTFFB"
QLOAPPS_BASE_URL = "http://localhost/qloapps/api"


TWILIO_ACCOUNT_SID = "YOUR_TWILIO_SID"
TWILIO_AUTH_TOKEN = "YOUR_TWILIO_AUTH_TOKEN"
TWILIO_FROM = "whatsapp:+1234567890"
DEFAULT_NOTIFICATION_TO = "whatsapp:+1234567890"


RAG_FOLDER = "rag_store"
EMBEDDING_DIM = 384


DEBUG_MODE = False
